apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: git-sync-patch.yaml
    target:
      kind: Notebook
      name: predictor-culpabilidad-wb